# Generated by Django 2.2 on 2023-10-14 11:18

import diary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20230919_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(validators=[diary.validators.validation_no_hash]),
        ),
        migrations.AlterField(
            model_name='page',
            name='feeling',
            field=models.CharField(max_length=80, validators=[diary.validators.validation_no_hash, diary.validators.validate_no_numbers]),
        ),
        migrations.AlterField(
            model_name='page',
            name='score',
            field=models.IntegerField(validators=[diary.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, validators=[diary.validators.validation_no_hash]),
        ),
    ]
